name: Commune
main: org.cyberpwn.commune.Commune
version: ${project.version}
depend: [Phantom, PlaceholderAPI, Vault]
softdepend: [ASkyBlock, SilkSpawners]
commands: 
  papyrus:
    aliases: [pap, paper]
  frtp:
    aliases: [wild, rtp, randomtp]
  ssx:
    aliases: [ssf, fss]